apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secrets
  namespace: {{ .Values.common.name }}
type: Opaque
data:
{{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | b64enc | quote }}
{{- end }}