common:
  createNamespace: true
  name: todoapp

todoapp:
  rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  containers:
      name: todoapp
      image: ikulyk404/todoapp
      version: 4.0.1
  resources:
    requests:
      memory: "256Mi"
      cpu: "150m"
    limits:
      memory: "256Mi"
      cpu: "150m"
  secrets:
    SECRET_KEY: "@e2(yx)v&tgh3_s=0yja-a!dpebxsz^dg47x)-k&kq_3zf*9e*"
    DB_NAME: "app_db"
    DB_USER: "app_user"
    DB_PASSWORD: "1234"
    DB_HOST: "mysql-0.mysql.mysql.svc.cluster.local"
  config:
    PYTHONUNBUFFERED: "1"
  nodeAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 1
      preference:
        matchExpressions:
        - key: app
          operator: In
          values:
          - kube2py
  hpa:
    enabled: true
    minReplicas: 2
    maxReplicas: 5
    cpu:
      targetAverageUtilization: 70
    memory:
      targetAverageUtilization: 70
  pv:
    storage: 1Gi
  pvc:
    storage: 1Gi
  rbac:
    srviceAccountName: secrets-reader