apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.common.name }}
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: {{ .Values.todoapp.rollingUpdate.maxSurge }}
      maxUnavailable: {{ .Values.todoapp.rollingUpdate.maxUnavailable }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      serviceAccountName: {{ .Values.todoapp.rbac.srviceAccountName }}
      containers:
      {{- with .Values.todoapp }}
      - name: {{ .containers.name }}
        image: {{ .containers.image }}:{{ .containers.version }}
        volumeMounts:
        - name: data
          mountPath: /app/data
        - name: {{ $.Chart.Name }}-secrets-volume
          mountPath: "/app/secrets"
          readOnly: true
        - name: {{ $.Chart.Name }}-config-volume
          mountPath: "/app/configs"
          readOnly: true
          resources:
            limits:
              memory: {{ .resources.limits.memory }}
              cpu: {{ .resources.limits.cpu }}
            requests:
              memory: {{ .resources.requests.memory }}
              cpu: {{ .resources.requests.cpu }}
        {{- end }}
        env:
        - name: PYTHONUNBUFFERED
          valueFrom:
            configMapKeyRef:
              name: {{ .Chart.Name }}-config
              key: PYTHONUNBUFFERED
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Chart.Name }}-secret
              key: SECRET_KEY
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: {{ .Chart.Name }}-secret
              key: DB_NAME
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: {{ .Chart.Name }}-secret
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Chart.Name }}-secret
              key: DB_PASSWORD
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: {{ .Chart.Name }}-secret
              key: DB_HOST
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: api/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: api/ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: pvc-data
      - name: {{ .Chart.Name }}-secrets-volume
        secret:
          secretName: app-secret
      - name: {{ .Chart.Name }}-config-volume
        configMap:
          name: {{ .Chart.Name }}-config
      affinity:
        nodeAffinity:
          {{- toYaml .Values.todoapp.nodeAffinity | nindent 8 }}