apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: {{ .Values.common.name }}
type: Opaque
data:
  {{- range $key, $value := .Values.todoapp.secrets }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}